--require("masonf.set")
--require("masonf.pack")
--require("masonf.map")
--require("masonf.cmp")
--require("masonf.mason")
--require("masonf.lualine")
--require("masonf.treesitter")

require("masonf_new.set")
require("masonf_new.lazy_init")
require("masonf_new.map")
--require("masonf_new.cmp")
